//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asDAsdasdaSD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int Id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Max_sale { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public Nullable<int> Supplier { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> Kolvo { get; set; }
        public string Opisanie { get; set; }
        public string Image { get; set; }
    }
}
