//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asDAsdasdaSD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int Id { get; set; }
        public Nullable<int> Num_zakaz { get; set; }
        public Nullable<int> Sostav { get; set; }
        public Nullable<int> Kolvo { get; set; }
        public Nullable<System.DateTime> Date_zakaz { get; set; }
        public Nullable<System.DateTime> Date_dostavka { get; set; }
        public Nullable<int> Punkt { get; set; }
        public string Fio { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
